QLESS.Web.UI/Controllers/AdminDashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace QLESS.Web.UI.Controllers
{
     [Authorize]
    public class AdminDashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

QLESS.Web.UI/Controllers/KioskDashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace QLESS.Web.UI.Controllers
{
    public class KioskDashboardController : Controller
    {


        public IActionResult Index()
        {
            return View();
        }


    }
}

QLESS.Web.UI/Controllers/RAWSMARTCARDsController.cs
using Common;
using Common.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace QLESS.Web.UI.Controllers
{
    public class RAWSMARTCARDsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RAWSMARTCARDsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: RAWSMARTCARDs
        public async Task<IActionResult> Index()
        {
            return View(await _context.RAWSMARTCARDs.ToListAsync());
        }

        // GET: RAWSMARTCARDs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rAWSMARTCARD = await _context.RAWSMARTCARDs
                .FirstOrDefaultAsync(m => m.SmartCardID == id);
            if (rAWSMARTCARD == null)
            {
                return NotFound();
            }

            return View(rAWSMARTCARD);
        }

        // GET: RAWSMARTCARDs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RAWSMARTCARDs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SmartCardID,SmartCardName,SerialNumber,IsActive,ActivatedDate,DeactivatedDate,IsValid,RowVersion")] RAWSMARTCARD rAWSMARTCARD)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rAWSMARTCARD);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rAWSMARTCARD);
        }

        // GET: RAWSMARTCARDs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rAWSMARTCARD = await _context.RAWSMARTCARDs.FindAsync(id);
            if (rAWSMARTCARD == null)
            {
                return NotFound();
            }
            return View(rAWSMARTCARD);
        }

        // POST: RAWSMARTCARDs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SmartCardID,SmartCardName,SerialNumber,IsActive,ActivatedDate,DeactivatedDate,IsValid,RowVersion")] RAWSMARTCARD rAWSMARTCARD)
        {
            if (id != rAWSMARTCARD.SmartCardID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rAWSMARTCARD);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RAWSMARTCARDExists(rAWSMARTCARD.SmartCardID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rAWSMARTCARD);
        }

        // GET: RAWSMARTCARDs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rAWSMARTCARD = await _context.RAWSMARTCARDs
                .FirstOrDefaultAsync(m => m.SmartCardID == id);
            if (rAWSMARTCARD == null)
            {
                return NotFound();
            }

            return View(rAWSMARTCARD);
        }

        // POST: RAWSMARTCARDs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rAWSMARTCARD = await _context.RAWSMARTCARDs.FindAsync(id);
            _context.RAWSMARTCARDs.Remove(rAWSMARTCARD!);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RAWSMARTCARDExists(int id)
        {
            return _context.RAWSMARTCARDs.Any(e => e.SmartCardID == id);
        }
    }
}

QLESS.Web.UI/Views/Shared/_Layout.cshtml
@using Common
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QLESS</title>
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QLESS.Web.UI.styles.css" asp-append-version="true" />


</head>
<body>
    <header style="background-color: midnightblue;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" style="padding: 5px;" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/serverfiles/images/qless.png" alt="logo" class="nav-pills" style="max-height: 40px;">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="KioskDashboard" asp-action="Index">KIOSK</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" href="~/swagger/index.html"><i class="fa fa-address-card"></i> SwaggerUI</a>
                        </li>

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link text-light dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-gear"></i> MANAGE</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="" asp-controller="TransportCards" asp-action="Index"><i class="fa fa-credit-card"></i>&nbsp;TRANSPORTCARDS</a>
                                    </li>
                                       <li class="nav-item">
                                        <a class="dropdown-item" asp-area="" asp-controller="RAWSMARTCARDs" asp-action="Index"><i class="fa fa-credit-card"></i>&nbsp;RAWCARDS</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="" asp-controller="Employees" asp-action="Index">
                                            <i class="fa fa-users"></i>&nbsp;Employees
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" id="register" asp-area="Identity" asp-page="/Account/Register">Register</a>
                                    </li>
                                    <li>
                                        @*  <a class="dropdown-item" asp-area="" asp-controller="RoleViews" asp-action="Admin">Admin</a>*@
                                        <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index">AppUsers</a>
                                    </li>
                                </ul>
                            </li>

                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - QLESS Transport Exam App by: Baron
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

QLESS.Web.UI/Views/Shared/_LayoutDefault.cshtml
@using Common
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QLESS</title>
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QLESS.Web.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header style="background-color: midnightblue;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" style="padding: 5px;" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/serverfiles/images/qless.png" alt="logo" class="nav-pills" style="max-height: 40px;">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="KioskDashboard" asp-action="Index">KIOSK</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="AdminDashboard" asp-action="Index">ADMIN</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - QLESS Transport Exam App by: Baron
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

QLESS.Web.UI/Views/Shared/_LayoutKiosk.cshtml
@using Common
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QLESS</title>
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QLESS.Web.UI.styles.css" asp-append-version="true" />
    <style type="text/css">
      
    </style>
</head>
<body>
    <header style="background-color: midnightblue;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" style="padding: 5px;" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/serverfiles/images/qless.png" alt="logo" class="nav-pills" style="max-height: 40px;">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="AdminDashboard" asp-action="Index">ADMIN</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - QLESS Transport Exam App by: Baron
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>